library(data.table)
library(lubridate)
quickRead <- fread(file = "household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors = FALSE,na.strings = "?")
twoDaysData <- subset(quickRead,Date=='1/2/2007'| Date=='2/2/2007')
twoDaysData$Date <- dmy_hms(paste(twoDaysData$Date,twoDaysData$Time))
png(filename = "plot2.png",width = 480, height = 480, units = "px")
plot(twoDaysData$Date, twoDaysData$Global_active_power,type="n",xlab="",ylab="Global Active Power(kilowatts)")
lines(twoDaysData$Date,twoDaysData$Global_active_power)
dev.off()
dev.set(2)
rm(quickRead,twoDaysData)

