library(data.table)
library(lubridate)
quickRead <- fread(file = "household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors = FALSE,na.strings = "?")
twoDaysData <- subset(quickRead,Date=='1/2/2007'| Date=='2/2/2007')
twoDaysData$Date <- dmy_hms(paste(twoDaysData$Date,twoDaysData$Time))
png(filename = "plot3.png",width = 480, height = 480, units = "px")
plot(twoDaysData$Date, twoDaysData$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
lines(twoDaysData$Date,twoDaysData$Sub_metering_1)
lines(twoDaysData$Date,twoDaysData$Sub_metering_2,col="red")
lines(twoDaysData$Date,twoDaysData$Sub_metering_3,col="blue")
legend("topright",lty=1,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"))
dev.off()
dev.set(2)
rm(quickRead,twoDaysData)

